### ISSUE TITLE
Dist fails on vanilla template

### ISSUE THREAD

**Issue by noroutine** [reZach/secure-electron-template#78]
Please provide the following information:

**Operating system**:  macOS 10.15.7 (Catalina)
**Version of the template**: master

Please have a MVP (minimal viable product/example) that can reproduce the bug consistently. If you do not have a MVP, the issue will not get as much attention to fixing.

Thank you for taking the time to help make this project better.

Hi
Was trying the template and immediately hit this.

Cloning and running template works fine, but dist fails with error
```
webpack 5.35.0 compiled with 2 warnings in 23206 ms
  • electron-builder  version=22.10.5 os=19.6.0
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=dist/builder-effective-config.yaml
  • packaging       platform=darwin arch=x64 electron=12.0.5 appOutDir=dist/mac
  • Unpacking electron zip  zipPath=undefined
  ⨯ editions-autoloader-none-broadened: Unable to determine a suitable edition, even after broadening.  stackTrace=
                                                                                                          Error: editions-autoloader-none-broadened: Unable to determine a suitable edition, even after broadening.
                                                                                                              at new Errlop (/Users/oleksii/noroutine/develop/secure-electron-template/node_modules/errlop/edition-es5/index.js:61:18)
                                                                                                              at Object.errtion (/Users/oleksii/noroutine/develop/secure-electron-template/node_modules/editions/edition-es5/util.js:23:14)
                                                                                                              at determineEdition (/Users/oleksii/noroutine/develop/secure-electron-template/node_modules/editions/edition-es5/index.js:317:21)
                                                                                                              at solicitEdition (/Users/oleksii/noroutine/develop/secure-electron-template/node_modules/editions/edition-es5/index.js:350:16)
                                                                                                              at Object.requirePackage (/Users/oleksii/noroutine/develop/secure-electron-template/node_modules/editions/edition-es5/index.js:364:9)
                                                                                                              at Object.<anonymous> (/Users/oleksii/noroutine/develop/secure-electron-template/node_modules/istextorbinary/index.cjs:4:38)
                                                                                                              at Module._compile (node:internal/modules/cjs/loader:1108:14)
                                                                                                              at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
                                                                                                              at Module.load (node:internal/modules/cjs/loader:988:32)
                                                                                                              at Function.Module._load (node:internal/modules/cjs/loader:828:14)
                                                                                                              at Module.require (node:internal/modules/cjs/loader:1012:19)
                                                                                                              at require (node:internal/modules/cjs/helpers:93:18)
                                                                                                              at Object.<anonymous> (/Users/oleksii/noroutine/develop/secure-electron-template/node_modules/app-builder-lib/electron-osx-sign/util.js:135:22)
                                                                                                              at Module._compile (node:internal/modules/cjs/loader:1108:14)
                                                                                                              at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
                                                                                                              at Module.load (node:internal/modules/cjs/loader:988:32)
                                                                                                          ↳ Error: editions-autoloader-none-suitable: Unable to determine a suitable edition, as none were suitable.
                                                                                                              at new Errlop (/Users/oleksii/noroutine/develop/secure-electron-template/node_modules/errlop/edition-es5/index.js:61:18)
                                                                                                              at Object.errtion (/Users/oleksii/noroutine/develop/secure-electron-template/node_modules/editions/edition-es5/util.js:23:14)
                                                                                                              at determineEdition (/Users/oleksii/noroutine/develop/secure-electron-template/node_modules/editions/edition-es5/index.js:327:19)
                                                                                                              at determineEdition (/Users/oleksii/noroutine/develop/secure-electron-template/node_modules/editions/edition-es5/index.js:312:12)
                                                                                                              at solicitEdition (/Users/oleksii/noroutine/develop/secure-electron-template/node_modules/editions/edition-es5/index.js:350:16)
                                                                                                              at Object.requirePackage (/Users/oleksii/noroutine/develop/secure-electron-template/node_modules/editions/edition-es5/index.js:364:9)
                                                                                                              at Object.<anonymous> (/Users/oleksii/noroutine/develop/secure-electron-template/node_modules/istextorbinary/index.cjs:4:38)
                                                                                                              at Module._compile (node:internal/modules/cjs/loader:1108:14)
                                                                                                              at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
                                                                                                              at Module.load (node:internal/modules/cjs/loader:988:32)
                                                                                                              at Function.Module._load (node:internal/modules/cjs/loader:828:14)
                                                                                                              at Module.require (node:internal/modules/cjs/loader:1012:19)
                                                                                                              at require (node:internal/modules/cjs/helpers:93:18)
                                                                                                              at Object.<anonymous> (/Users/oleksii/noroutine/develop/secure-electron-template/node_modules/app-builder-lib/electron-osx-sign/util.js:135:22)
                                                                                                              at Module._compile (node:internal/modules/cjs/loader:1108:14)
                                                                                                              at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
                                                                                                          ↳ Error: editions-autoloader-edition-incompatible: editions-autoloader-edition-incompatible: The edition [TypeScript source code made to be compatible with Deno] is not compatible with this environment.
                                                                                                              at new Errlop (/Users/oleksii/noroutine/develop/secure-electron-template/node_modules/errlop/edition-es5/index.js:61:18)
                                                                                                              at Object.errtion (/Users/oleksii/noroutine/develop/secure-electron-template/node_modules/editions/edition-es5/util.js:23:14)
                                                                                                              at determineEdition (/Users/oleksii/noroutine/develop/secure-electron-template/node_modules/editions/edition-es5/index.js:301:25)
                                                                                                              at determineEdition (/Users/oleksii/noroutine/develop/secure-electron-template/node_modules/editions/edition-es5/index.js:312:12)
                                                                                                              at solicitEdition (/Users/oleksii/noroutine/develop/secure-electron-template/node_modules/editions/edition-es5/index.js:350:16)
                                                                                                              at Object.requirePackage (/Users/oleksii/noroutine/develop/secure-electron-template/node_modules/editions/edition-es5/index.js:364:9)
                                                                                                              at Object.<anonymous> (/Users/oleksii/noroutine/develop/secure-electron-template/node_modules/istextorbinary/index.cjs:4:38)
                                                                                                              at Module._compile (node:internal/modules/cjs/loader:1108:14)
                                                                                                              at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
                                                                                                              at Module.load (node:internal/modules/cjs/loader:988:32)
                                                                                                              at Function.Module._load (node:internal/modules/cjs/loader:828:14)
                                                                                                              at Module.require (node:internal/modules/cjs/loader:1012:19)
                                                                                                              at require (node:internal/modules/cjs/helpers:93:18)
                                                                                                              at Object.<anonymous> (/Users/oleksii/noroutine/develop/secure-electron-template/node_modules/app-builder-lib/electron-osx-sign/util.js:135:22)
                                                                                                              at Module._compile (node:internal/modules/cjs/loader:1108:14)
                                                                                                              at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
                                                                                                          ↳ Error: editions-autoloader-edition-incompatible: editions-autoloader-edition-incompatible: The edition [TypeScript compiled against ES2019 for Node.js 12 || 14 || 15 with Import for modules] is not compatible with this environment.
                                                                                                              at new Errlop (/Users/oleksii/noroutine/develop/secure-electron-template/node_modules/errlop/edition-es5/index.js:61:18)
                                                                                                              at Object.errtion (/Users/oleksii/noroutine/develop/secure-electron-template/node_modules/editions/edition-es5/util.js:23:14)
                                                                                                              at determineEdition (/Users/oleksii/noroutine/develop/secure-electron-template/node_modules/editions/edition-es5/index.js:301:25)
                                                                                                              at determineEdition (/Users/oleksii/noroutine/develop/secure-electron-template/node_modules/editions/edition-es5/index.js:312:12)
                                                                                                              at solicitEdition (/Users/oleksii/noroutine/develop/secure-electron-template/node_modules/editions/edition-es5/index.js:350:16)
                                                                                                              at Object.requirePackage (/Users/oleksii/noroutine/develop/secure-electron-template/node_modules/editions/edition-es5/index.js:364:9)
                                                                                                              at Object.<anonymous> (/Users/oleksii/noroutine/develop/secure-electron-template/node_modules/istextorbinary/index.cjs:4:38)
                                                                                                              at Module._compile (node:internal/modules/cjs/loader:1108:14)
                                                                                                              at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
                                                                                                              at Module.load (node:internal/modules/cjs/loader:988:32)
                                                                                                              at Function.Module._load (node:internal/modules/cjs/loader:828:14)
                                                                                                              at Module.require (node:internal/modules/cjs/loader:1012:19)
                                                                                                              at require (node:internal/modules/cjs/helpers:93:18)
                                                                                                              at Object.<anonymous> (/Users/oleksii/noroutine/develop/secure-electron-template/node_modules/app-builder-lib/electron-osx-sign/util.js:135:22)
                                                                                                              at Module._compile (node:internal/modules/cjs/loader:1108:14)
                                                                                                              at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
                                                                                                          ↳ Error: editions-autoloader-edition-incompatible: editions-autoloader-edition-incompatible: The edition [TypeScript compiled against ES2019 for Node.js 10 || 12 || 14 || 15 with Require for modules] is not compatible with this environment.
                                                                                                              at new Errlop (/Users/oleksii/noroutine/develop/secure-electron-template/node_modules/errlop/edition-es5/index.js:61:18)
                                                                                                              at Object.errtion (/Users/oleksii/noroutine/develop/secure-electron-template/node_modules/editions/edition-es5/util.js:23:14)
                                                                                                              at determineEdition (/Users/oleksii/noroutine/develop/secure-electron-template/node_modules/editions/edition-es5/index.js:301:25)
                                                                                                              at determineEdition (/Users/oleksii/noroutine/develop/secure-electron-template/node_modules/editions/edition-es5/index.js:312:12)
                                                                                                              at solicitEdition (/Users/oleksii/noroutine/develop/secure-electron-template/node_modules/editions/edition-es5/index.js:350:16)
                                                                                                              at Object.requirePackage (/Users/oleksii/noroutine/develop/secure-electron-template/node_modules/editions/edition-es5/index.js:364:9)
                                                                                                              at Object.<anonymous> (/Users/oleksii/noroutine/develop/secure-electron-template/node_modules/istextorbinary/index.cjs:4:38)
                                                                                                              at Module._compile (node:internal/modules/cjs/loader:1108:14)
                                                                                                              at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
                                                                                                              at Module.load (node:internal/modules/cjs/loader:988:32)
                                                                                                              at Function.Module._load (node:internal/modules/cjs/loader:828:14)
                                                                                                              at Module.require (node:internal/modules/cjs/loader:1012:19)
                                                                                                              at require (node:internal/modules/cjs/helpers:93:18)
                                                                                                              at Object.<anonymous> (/Users/oleksii/noroutine/develop/secure-electron-template/node_modules/app-builder-lib/electron-osx-sign/util.js:135:22)
                                                                                                              at Module._compile (node:internal/modules/cjs/loader:1108:14)
                                                                                                              at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
                                                                                                          ↳ Error: editions-autoloader-edition-incompatible: editions-autoloader-edition-incompatible: The edition [TypeScript compiled against ESNext for Node.js 14 || 15 with Require for modules] is not compatible with this environment.
                                                                                                              at new Errlop (/Users/oleksii/noroutine/develop/secure-electron-template/node_modules/errlop/edition-es5/index.js:61:18)
                                                                                                              at Object.errtion (/Users/oleksii/noroutine/develop/secure-electron-template/node_modules/editions/edition-es5/util.js:23:14)
                                                                                                              at determineEdition (/Users/oleksii/noroutine/develop/secure-electron-template/node_modules/editions/edition-es5/index.js:301:25)
                                                                                                              at determineEdition (/Users/oleksii/noroutine/develop/secure-electron-template/node_modules/editions/edition-es5/index.js:312:12)
                                                                                                              at solicitEdition (/Users/oleksii/noroutine/develop/secure-electron-template/node_modules/editions/edition-es5/index.js:350:16)
                                                                                                              at Object.requirePackage (/Users/oleksii/noroutine/develop/secure-electron-template/node_modules/editions/edition-es5/index.js:364:9)
                                                                                                              at Object.<anonymous> (/Users/oleksii/noroutine/develop/secure-electron-template/node_modules/istextorbinary/index.cjs:4:38)
                                                                                                              at Module._compile (node:internal/modules/cjs/loader:1108:14)
                                                                                                              at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
                                                                                                              at Module.load (node:internal/modules/cjs/loader:988:32)
                                                                                                              at Function.Module._load (node:internal/modules/cjs/loader:828:14)
                                                                                                              at Module.require (node:internal/modules/cjs/loader:1012:19)
                                                                                                              at require (node:internal/modules/cjs/helpers:93:18)
                                                                                                              at Object.<anonymous> (/Users/oleksii/noroutine/develop/secure-electron-template/node_modules/app-builder-lib/electron-osx-sign/util.js:135:22)
                                                                                                              at Module._compile (node:internal/modules/cjs/loader:1108:14)
                                                                                                              at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
                                                                                                          ↳ Error: editions-autoloader-edition-incompatible: editions-autoloader-edition-incompatible: The edition [TypeScript compiled against ES2019 for web browsers with Import for modules] is not compatible with this environment.
                                                                                                              at new Errlop (/Users/oleksii/noroutine/develop/secure-electron-template/node_modules/errlop/edition-es5/index.js:61:18)
                                                                                                              at Object.errtion (/Users/oleksii/noroutine/develop/secure-electron-template/node_modules/editions/edition-es5/util.js:23:14)
                                                                                                              at determineEdition (/Users/oleksii/noroutine/develop/secure-electron-template/node_modules/editions/edition-es5/index.js:301:25)
                                                                                                              at determineEdition (/Users/oleksii/noroutine/develop/secure-electron-template/node_modules/editions/edition-es5/index.js:312:12)
                                                                                                              at solicitEdition (/Users/oleksii/noroutine/develop/secure-electron-template/node_modules/editions/edition-es5/index.js:350:16)
                                                                                                              at Object.requirePackage (/Users/oleksii/noroutine/develop/secure-electron-template/node_modules/editions/edition-es5/index.js:364:9)
                                                                                                              at Object.<anonymous> (/Users/oleksii/noroutine/develop/secure-electron-template/node_modules/istextorbinary/index.cjs:4:38)
                                                                                                              at Module._compile (node:internal/modules/cjs/loader:1108:14)
                                                                                                              at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
                                                                                                              at Module.load (node:internal/modules/cjs/loader:988:32)
                                                                                                              at Function.Module._load (node:internal/modules/cjs/loader:828:14)
                                                                                                              at Module.require (node:internal/modules/cjs/loader:1012:19)
                                                                                                              at require (node:internal/modules/cjs/helpers:93:18)
                                                                                                              at Object.<anonymous> (/Users/oleksii/noroutine/develop/secure-electron-template/node_modules/app-builder-lib/electron-osx-sign/util.js:135:22)
                                                                                                              at Module._compile (node:internal/modules/cjs/loader:1108:14)
                                                                                                              at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
                                                                                                          ↳ Error: editions-autoloader-edition-incompatible: The edition [TypeScript source code with Import for modules] is not compatible with this environment.
                                                                                                              at new Errlop (/Users/oleksii/noroutine/develop/secure-electron-template/node_modules/errlop/edition-es5/index.js:61:18)
                                                                                                              at Object.errtion (/Users/oleksii/noroutine/develop/secure-electron-template/node_modules/editions/edition-es5/util.js:23:14)
                                                                                                              at isCompatibleEdition (/Users/oleksii/noroutine/develop/secure-electron-template/node_modules/editions/edition-es5/index.js:252:19)
                                                                                                              at determineEdition (/Users/oleksii/noroutine/develop/secure-electron-template/node_modules/editions/edition-es5/index.js:287:4)
                                                                                                              at determineEdition (/Users/oleksii/noroutine/develop/secure-electron-template/node_modules/editions/edition-es5/index.js:312:12)
                                                                                                              at solicitEdition (/Users/oleksii/noroutine/develop/secure-electron-template/node_modules/editions/edition-es5/index.js:350:16)
                                                                                                              at Object.requirePackage (/Users/oleksii/noroutine/develop/secure-electron-template/node_modules/editions/edition-es5/index.js:364:9)
                                                                                                              at Object.<anonymous> (/Users/oleksii/noroutine/develop/secure-electron-template/node_modules/istextorbinary/index.cjs:4:38)
                                                                                                              at Module._compile (node:internal/modules/cjs/loader:1108:14)
                                                                                                              at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
                                                                                                              at Module.load (node:internal/modules/cjs/loader:988:32)
                                                                                                              at Function.Module._load (node:internal/modules/cjs/loader:828:14)
                                                                                                              at Module.require (node:internal/modules/cjs/loader:1012:19)
                                                                                                              at require (node:internal/modules/cjs/helpers:93:18)
                                                                                                              at Object.<anonymous> (/Users/oleksii/noroutine/develop/secure-electron-template/node_modules/app-builder-lib/electron-osx-sign/util.js:135:22)
                                                                                                              at Module._compile (node:internal/modules/cjs/loader:1108:14)
                                                                                                          ↳ Error: editions-autoloader-invalid-engines: The edition had no engines to compare against the environment
                                                                                                              at new Errlop (/Users/oleksii/noroutine/develop/secure-electron-template/node_modules/errlop/edition-es5/index.js:61:18)
                                                                                                              at Object.errtion (/Users/oleksii/noroutine/develop/secure-electron-template/node_modules/editions/edition-es5/util.js:23:14)
                                                                                                              at isCompatibleEngines (/Users/oleksii/noroutine/develop/secure-electron-template/node_modules/editions/edition-es5/index.js:183:19)
                                                                                                              at isCompatibleEdition (/Users/oleksii/noroutine/develop/secure-electron-template/node_modules/editions/edition-es5/index.js:250:10)
                                                                                                              at determineEdition (/Users/oleksii/noroutine/develop/secure-electron-template/node_modules/editions/edition-es5/index.js:287:4)
                                                                                                              at determineEdition (/Users/oleksii/noroutine/develop/secure-electron-template/node_modules/editions/edition-es5/index.js:312:12)
                                                                                                              at solicitEdition (/Users/oleksii/noroutine/develop/secure-electron-template/node_modules/editions/edition-es5/index.js:350:16)
                                                                                                              at Object.requirePackage (/Users/oleksii/noroutine/develop/secure-electron-template/node_modules/editions/edition-es5/index.js:364:9)
                                                                                                              at Object.<anonymous> (/Users/oleksii/noroutine/develop/secure-electron-template/node_modules/istextorbinary/index.cjs:4:38)
                                                                                                              at Module._compile (node:internal/modules/cjs/loader:1108:14)
                                                                                                              at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
                                                                                                              at Module.load (node:internal/modules/cjs/loader:988:32)
                                                                                                              at Function.Module._load (node:internal/modules/cjs/loader:828:14)
                                                                                                              at Module.require (node:internal/modules/cjs/loader:1012:19)
                                                                                                              at require (node:internal/modules/cjs/helpers:93:18)
                                                                                                              at Object.<anonymous> (/Users/oleksii/noroutine/develop/secure-electron-template/node_modules/app-builder-lib/electron-osx-sign/util.js:135:22)
error Command failed with exit code 1.
```

Anything I can do from my side?

**Comment by reZach** [comment]
Thanks for reporting @noroutine , what's your node version?
[Reference](https://github.com/electron-userland/electron-builder/issues/5668)

**Comment by noroutine** [comment]
@reZach spot on, have v16, seems it's indeed new builder issue with new node, works fine when downgrading either of them

I mean node v16 builds fine with builder v22.10.4

**Comment by reZach** [comment]
@noroutine There was an update to electron-builder recently, [this release](https://github.com/reZach/secure-electron-template/releases/tag/v11.0.0) has the fix, or you can update **electron-builder** in your own project. I'm going to close assuming this fixes it for you, please re-open if it doesn't.
